[package]
name = "rustos"
version = "0.0.1"
authors = [ "you@example.com" ]

[lib]
name = "rustos"
crate-type = [ "staticlib" ]


[dependencies.core]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust.git"
branch = "rustos"

[dependencies.alloc]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust.git"
branch = "rustos"
default-features = false
features = [ "external_crate" ]

[dependencies.collections]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust.git"
branch = "rustos"


[dependencies.bitflags]
git = "http://github.com/RustOS-Fork-Holding-Ground/bitflags.git"
branch = "rustos"

[dependencies.external]
path = "bump-pointer"

[dependencies.lazy-static-spin]
git = "https://github.com/RustOS-Fork-Holding-Ground/lazy-static-spin"
branch = "rustos"

[dependencies.spin]
git = "https://github.com/RustOS-Fork-Holding-Ground/spinlock-rs"
branch = "rustos"

[dependencies.rlibc]
rlibc = "https://github.com/RustOS-Fork-Holding-Ground/rlibc"
branch = "rustos"
